---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(VISION)
library(Matrix)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(gridExtra)

rauch_d0=Read10X(data.dir = "~/summary_time_series/revisions/R2_C9/data/rauch et al. 2019/d0_bm_msc/")
rauch_d0=CreateSeuratObject(counts = rauch_d0,project = "d0")
rauch_d7=Read10X(data.dir = "~/summary_time_series/revisions/R2_C9/data/rauch et al. 2019/d7_bm_msc/")
rauch_d7=CreateSeuratObject(counts = rauch_d7,project = "d7")
rauch.combined <- merge(rauch_d0, y = rauch_d7, add.cell.ids = c("d0", "d7"), project = "rauch.combined")
rauch.combined=NormalizeData(rauch.combined)
rauch.combined=FindVariableFeatures(rauch.combined)
rauch.combined=ScaleData(rauch.combined)
rauch.combined=RunPCA(rauch.combined)
rauch.combined=RunUMAP(rauch.combined,dims = 1:30)

load("~/summary_time_series/revisions/R2_C9/v1.RData")
p1=UMAPPlot(rauch.combined,group.by="orig.ident",pt.size=2)+theme_classic(base_size = 10)
p1+theme_void()+scale_color_manual(values = c("navyblue","goldenrod"))
ggsave(filename = "rauch_day.tiff",path = "~/summary_time_series/revisions/R2_C9/tiffs/", width = 7.5, height = 5.5, device='tiff', dpi=300,units = "in")
```

```{r}
source(file = "~/time-series/RNotebook/scripts/custom_functions.R")

load("~/summary_time_series/RData/white/slingshot_ugenes_de.RData")
load("~/summary_time_series/RData/white/vision_ugenes_de.RData")

# Create vision signature
sigu=vector(mode = "double",length = length(intersect(sugenes_de,vugenes_de)))
sigu[]=1
names(sigu)=intersect(sugenes_de,vugenes_de)
sig=sigu
sig <- createGeneSignature(name = "Adipo_Ordering", sigData = sig)
Signatures=c(sig)

vis=vision(s.object = rauch.combined,sig = Signatures,addUMAP = F)
```

```{r}
#rauch.combined$score=vis@SigScores[,1]
ggplot(rauch.combined@meta.data,aes(x=range01(score),fill=orig.ident))+geom_histogram(aes(y=..density..),position = position_dodge(),color="black",alpha=1)+theme_classic(base_size = 20)+geom_density(alpha=.5)+theme(legend.position = "top")+scale_fill_manual(values = c("navyblue","goldenrod"))
ggsave(filename = "rauch_day_score.eps",path = "~/summary_time_series/revisions/R2_C9/tiffs/", width = 7.5, height = 5.5, device='eps', dpi=300,units = "in")
```

```{r}
p3=FeaturePlot(object = rauch.combined,features = "THY1")+theme_classic(base_size = 10)
p4=FeaturePlot(object = rauch.combined,features = "PDGFRA")+theme_classic(base_size = 10)
p5=FeaturePlot(object = rauch.combined,features = "ADIPOQ")+theme_classic(base_size = 10)
#rauch.combined=FindNeighbors(rauch.combined,dims = 1:30)
#rauch.combined=FindClusters(rauch.combined,resolution = .06)
UMAPPlot(rauch.combined,label=T,label.size=5,cols=c("red","forestgreen","navyblue","lightgreen","magenta"),pt.size=2)+theme_classic(base_size = 20)+theme_void()
ggsave(filename = "rauch_cluster.tiff",path = "~/summary_time_series/revisions/R2_C9/tiffs/", width = 7.5, height = 5.5, device='tiff', dpi=300,units = "in")
DotPlot(rauch.combined[,WhichCells(rauch.combined,idents = c(0,1,2))],features = c("THY1","PDGFRA","ADIPOQ"))
ggsave(filename = "rauch_dot.eps",path = "~/summary_time_series/revisions/R2_C9/tiffs/", width = 7.5, height = 5.5, device='eps', dpi=300,units = "in")
```

```{r}
#rauch.combined$score=vis@SigScores[,1]
ggplot(rauch.combined@meta.data[WhichCells(object = rauch.combined,idents = c(0,1,2)),],aes(x=range01(score),fill=seurat_clusters))+geom_histogram(aes(y=..density..),position = position_dodge(),color="black",alpha=1)+theme_classic(base_size = 10)+geom_density(alpha=.5)+theme(legend.position = "top")#+scale_fill_manual(values = c("red","forestgreen","lightgreen"))#+theme(legend.position = "none")
ggsave(filename = "rauch_cluster_score.eps",path = "~/summary_time_series/revisions/R2_C9/tiffs/", width = 7.5, height = 5.5, device='eps', dpi=300,units = "in")
```

```{r}
# load("~/summary_time_series/RData/white/gene_cluster_new.RData")
# sig=vector(mode = "list",length = 5)
# for (i in 0:4) {
# sigu=vector(mode = "double",length = sum(gene_cluster_new==i))
# sigu[]=1
# names(sigu)=names(gene_cluster_new)[gene_cluster_new==i]
# sig[[i+1]] <- createGeneSignature(name = as.character(i), sigData = sigu) 
# }
# Signatures=unlist(sig)
# vis1=vision(s.object = rauch.combined,sig = Signatures,addUMAP = F)
```

```{r}
#colnames(vis1@SigScores)=paste("gene_cluster",colnames(vis1@SigScores),sep = "_")
#rauch.combined@meta.data=cbind(rauch.combined@meta.data,vis1@SigScores)
plot.df=rauch.combined@meta.data[WhichCells(object = rauch.combined,idents = c(0,1,2)),c(grep("gene_cluster",x = colnames(rauch.combined@meta.data)),6)]
plot.df=select(plot.df,-"gene_cluster_2")
plot.df=gather(plot.df,"gene_cluster","score",-seurat_clusters)
ggplot(plot.df,aes(x=range01(score),fill=seurat_clusters))+geom_histogram(aes(y=..density..),position = position_dodge(),alpha=1)+facet_grid(.~ gene_cluster)+theme_light(base_size = 20)+geom_density(alpha=.5)+theme(legend.position = "none")+scale_fill_manual(values = c("red","forestgreen","navyblue"))#+theme(legend.position = "none")
ggsave(filename = "rauch_module.eps",path = "~/summary_time_series/revisions/R2_C9/tiffs/", width = 8.5, height = 4, device='eps', dpi=300,units = "in")
```

```{r}
# Arrange all plots
pdf(file = "~/summary_time_series/revisions/R2_C9/tiffs//1.pdf",width = 8.5,height = 6)
grid.arrange(p1,p2,p3,p4,p5,p6,p7,p8,ncol = 4, nrow = 3,layout_matrix = t(matrix(c(1:7,NA,replicate(n = 4,expr = 8)),nrow = 4,ncol = 3)))
dev.off()
```

